export { default as EmployeesManagement } from './admin/EmployeesManagerment/EmployeesManagementPage'
export { default as CreateNewEmployeePage } from './admin/EmployeesManagerment/CreateNewEmployeePage'
export { default as EditEmployeePage } from './admin/EmployeesManagerment/EditEmployeePage'
export { default as EmployeeDetailPage } from './admin/EmployeesManagerment/EmployeeDetailPage'

export { default as AttendancePage} from './attendance/AttendancePage'
export { default as AttendanceRequestPage } from './attendance_requests/AttendanceRequestsPage'
export { default as Login } from './auth/Login'
export { default as ContractPage } from './contract/ContractPage'
export { default as ContractDetail } from './contract/ContractDetail'
export { default as DashboardLayout } from './dashboard/Dashboard'
export { default as HolidayPage } from './holidays/HolidaysUI'
export { default as LeaveRequestPage } from './leave_requests/LeaveRequestsPage'
export { default as OvertimeRequestPage } from './overtime/OvertimeUI'
export { default as MyPayrollPage } from './payroll/PayrollPage'
export { default as PayrollDetailPage } from './payroll/PayrollDetail'
export { default as ProfilePage } from './profile/ProfilePage'
export { default as EditProfile } from './profile/EditProfile'
export { default as WorkCalendarPage } from './workcalendar/WorkCalendarUI'
export { default as WorkSchedulePage } from './workschedule/WorkSchedulePage'